-- 코드를 작성해주세요
SELECT
    E1.ID,
    COALESCE(E2.PRE_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA E1
LEFT JOIN (
    SELECT
        PARENT_ID,
        COUNT(*) AS PRE_COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
) E2
    ON E1.ID = E2.PARENT_ID
ORDER BY ID