-- 코드를 입력하세요
SELECT
DISTINCT
    C.CAR_ID,
    C.CAR_TYPE,
    ROUND(C.DAILY_FEE * ((100 - P.DISCOUNT_RATE) * 0.01) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE LIKE '30%'
    ) AS P 
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV') 
AND(C.DAILY_FEE * ((100 - P.DISCOUNT_RATE) * 0.01) * 30 >= 500000
AND C.DAILY_FEE * ((100 - P.DISCOUNT_RATE) * 0.01) * 30 < 2000000)
AND C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (START_DATE LIKE '2022-11-%' OR END_DATE LIKE '2022-11-%')
    OR (START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-30'))
ORDER BY 3 DESC, 2, 1 DESC