-- 코드를 입력하세요
WITH RECURSIVE db AS
(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT 1 + HOUR FROM db WHERE HOUR < 23
)
SELECT 
    D.HOUR,
    COUNT(A.DATETIME) AS 'COUNT'
FROM db D LEFT JOIN ANIMAL_OUTS A ON D.HOUR = HOUR(A.DATETIME)
GROUP BY HOUR