-- 코드를 작성해주세요
WITH Yearly_Max_Size AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
            MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
),
Variation AS (
    SELECT e.ID,
            YEAR(e.DIFFERENTIATION_DATE) AS YEAR,
            m.MAX_SIZE - e.SIZE_OF_COLONY AS SIZE_VARIATION
    FROM ECOLI_DATA e
    JOIN Yearly_Max_Size m ON YEAR(e.DIFFERENTIATION_DATE) = m.YEAR
)
SELECT YEAR,
        SIZE_VARIATION AS YEAR_DEV,
        ID
FROM Variation
ORDER BY YEAR ASC, SIZE_VARIATION ASC;