-- 코드를 작성해주세요
SELECT
    FISH_INFO.ID AS ID,
    FISH_NAME_INFO.FISH_NAME AS FISH_NAME,
    FISH_INFO.LENGTH AS LENGTH
FROM FISH_INFO
JOIN FISH_NAME_INFO ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
JOIN (
    SELECT
        FISH_TYPE,
        MAX(LENGTH) AS max_length
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS max_lengths ON FISH_INFO.FISH_TYPE = max_lengths.FISH_TYPE AND FISH_INFO.LENGTH = max_lengths.max_length
ORDER BY FISH_INFO.ID;
